CREATE TABLE livros (
  id INT PRIMARY KEY AUTO_INCREMENT,
  titulo VARCHAR(255) NOT NULL,
  autor VARCHAR(255) NOT NULL,
  genero VARCHAR(255) NOT NULL,
  foto BLOB,
  disponivel BOOLEAN NOT NULL,
  quantidade INT NOT NULL
);